-- ============================================
-- Türkiye'nin Tüm 81 İlini Ekleme
-- ============================================

-- Önce mevcut şehirleri temizle (varsa) ve yeniden ekle
-- ON CONFLICT ile var olanları güncelle, olmayanları ekle

INSERT INTO cities (id, name, plate, description, created_at, updated_at) VALUES
('adana', 'Adana', '01', NULL, NOW(), NOW()),
('adiyaman', 'Adıyaman', '02', NULL, NOW(), NOW()),
('afyonkarahisar', 'Afyonkarahisar', '03', NULL, NOW(), NOW()),
('agri', 'Ağrı', '04', NULL, NOW(), NOW()),
('amasya', 'Amasya', '05', NULL, NOW(), NOW()),
('ankara', 'Ankara', '06', NULL, NOW(), NOW()),
('antalya', 'Antalya', '07', NULL, NOW(), NOW()),
('artvin', 'Artvin', '08', NULL, NOW(), NOW()),
('aydin', 'Aydın', '09', NULL, NOW(), NOW()),
('balikesir', 'Balıkesir', '10', NULL, NOW(), NOW()),
('bilecik', 'Bilecik', '11', NULL, NOW(), NOW()),
('bingol', 'Bingöl', '12', NULL, NOW(), NOW()),
('bitlis', 'Bitlis', '13', NULL, NOW(), NOW()),
('bolu', 'Bolu', '14', NULL, NOW(), NOW()),
('burdur', 'Burdur', '15', NULL, NOW(), NOW()),
('bursa', 'Bursa', '16', NULL, NOW(), NOW()),
('canakkale', 'Çanakkale', '17', NULL, NOW(), NOW()),
('cankiri', 'Çankırı', '18', NULL, NOW(), NOW()),
('corum', 'Çorum', '19', NULL, NOW(), NOW()),
('denizli', 'Denizli', '20', NULL, NOW(), NOW()),
('diyarbakir', 'Diyarbakır', '21', NULL, NOW(), NOW()),
('edirne', 'Edirne', '22', NULL, NOW(), NOW()),
('elazig', 'Elazığ', '23', NULL, NOW(), NOW()),
('erzincan', 'Erzincan', '24', NULL, NOW(), NOW()),
('erzurum', 'Erzurum', '25', NULL, NOW(), NOW()),
('eskisehir', 'Eskişehir', '26', NULL, NOW(), NOW()),
('gaziantep', 'Gaziantep', '27', NULL, NOW(), NOW()),
('giresun', 'Giresun', '28', NULL, NOW(), NOW()),
('gumushane', 'Gümüşhane', '29', NULL, NOW(), NOW()),
('hakkari', 'Hakkari', '30', NULL, NOW(), NOW()),
('hatay', 'Hatay', '31', NULL, NOW(), NOW()),
('isparta', 'Isparta', '32', NULL, NOW(), NOW()),
('mersin', 'Mersin', '33', NULL, NOW(), NOW()),
('istanbul', 'İstanbul', '34', NULL, NOW(), NOW()),
('izmir', 'İzmir', '35', NULL, NOW(), NOW()),
('kars', 'Kars', '36', NULL, NOW(), NOW()),
('kastamonu', 'Kastamonu', '37', NULL, NOW(), NOW()),
('kayseri', 'Kayseri', '38', NULL, NOW(), NOW()),
('kirklareli', 'Kırklareli', '39', NULL, NOW(), NOW()),
('kirsehir', 'Kırşehir', '40', NULL, NOW(), NOW()),
('kocaeli', 'Kocaeli', '41', NULL, NOW(), NOW()),
('konya', 'Konya', '42', NULL, NOW(), NOW()),
('kutahya', 'Kütahya', '43', NULL, NOW(), NOW()),
('malatya', 'Malatya', '44', NULL, NOW(), NOW()),
('manisa', 'Manisa', '45', NULL, NOW(), NOW()),
('kahramanmaras', 'Kahramanmaraş', '46', NULL, NOW(), NOW()),
('mardin', 'Mardin', '47', NULL, NOW(), NOW()),
('mugla', 'Muğla', '48', NULL, NOW(), NOW()),
('mus', 'Muş', '49', NULL, NOW(), NOW()),
('nevsehir', 'Nevşehir', '50', NULL, NOW(), NOW()),
('nigde', 'Niğde', '51', NULL, NOW(), NOW()),
('ordu', 'Ordu', '52', NULL, NOW(), NOW()),
('rize', 'Rize', '53', NULL, NOW(), NOW()),
('sakarya', 'Sakarya', '54', NULL, NOW(), NOW()),
('samsun', 'Samsun', '55', NULL, NOW(), NOW()),
('siirt', 'Siirt', '56', NULL, NOW(), NOW()),
('sinop', 'Sinop', '57', NULL, NOW(), NOW()),
('sivas', 'Sivas', '58', NULL, NOW(), NOW()),
('tekirdag', 'Tekirdağ', '59', NULL, NOW(), NOW()),
('tokat', 'Tokat', '60', NULL, NOW(), NOW()),
('trabzon', 'Trabzon', '61', NULL, NOW(), NOW()),
('tunceli', 'Tunceli', '62', NULL, NOW(), NOW()),
('sanliurfa', 'Şanlıurfa', '63', NULL, NOW(), NOW()),
('usak', 'Uşak', '64', NULL, NOW(), NOW()),
('van', 'Van', '65', NULL, NOW(), NOW()),
('yozgat', 'Yozgat', '66', NULL, NOW(), NOW()),
('zonguldak', 'Zonguldak', '67', NULL, NOW(), NOW()),
('aksaray', 'Aksaray', '68', NULL, NOW(), NOW()),
('bayburt', 'Bayburt', '69', NULL, NOW(), NOW()),
('karaman', 'Karaman', '70', NULL, NOW(), NOW()),
('kirikkale', 'Kırıkkale', '71', NULL, NOW(), NOW()),
('batman', 'Batman', '72', NULL, NOW(), NOW()),
('sirnak', 'Şırnak', '73', NULL, NOW(), NOW()),
('bartin', 'Bartın', '74', NULL, NOW(), NOW()),
('ardahan', 'Ardahan', '75', NULL, NOW(), NOW()),
('igdir', 'Iğdır', '76', NULL, NOW(), NOW()),
('yalova', 'Yalova', '77', NULL, NOW(), NOW()),
('karabuk', 'Karabük', '78', NULL, NOW(), NOW()),
('kilis', 'Kilis', '79', NULL, NOW(), NOW()),
('osmaniye', 'Osmaniye', '80', NULL, NOW(), NOW()),
('duzce', 'Düzce', '81', NULL, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    plate = EXCLUDED.plate,
    updated_at = NOW();

-- Verify count
SELECT COUNT(*) as total_cities FROM cities;
