        paymentMethod: row.payment_method,
        paymentStatus: row.payment_status,
        status: row.order_status,
        customerNote: row.customer_note,
        couponCode: row.coupon_code,
        couponDiscount: typeof row.coupon_discount === 'string' ? parseFloat(row.coupon_discount) : row.coupon_discount,